AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda_newbiz_registration

  Gets data from NewBiz form and logs to the DW. Then forwards the request to SF.

Globals:
  Function:
    Timeout: 3

Resources:
  ReviewMeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: newbiz_registration
      CodeUri: function/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::025737178121:role/ExpertiseLambdas
      Architectures:
        - x86_64

Outputs:
  ReviewMeFunction:
    Description: "NewBiz Review Me Lambda Function ARN"
    Value: !GetAtt ReviewMeFunction.Arn
