AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  <CHANGE ME TO MATCH THE README.md>

Globals:
  Function:
    Timeout: 3

Resources:
  <CHANGE TO FUNCTION NAME>Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: <CHANGE TO FUNCTION NAME>
      CodeUri: <CHANGE TO FUNCTION URI>/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::025737178121:role/ExpertiseLambdas
      Architectures:
        - x86_64

Outputs:
  AHrefsFunction:
    Description: "<CHANGE ME TO MATCH THE PROJECT NAME> Lambda Function ARN"
    Value: !GetAtt <CHANGE TO FUNCTION NAME>Function.Arn
